### ISSUE TITLE
screenshot

### ISSUE THREAD

**Issue by Sahilberi** [Sahilberi/ImageTextField#1]
![screen shot 2017-02-22 at 2 35 11 pm](https://cloud.githubusercontent.com/assets/7422405/23204547/05a367f6-f90d-11e6-9a7e-4142f9ad7fd0.png)

**Comment by HuppDevelopers** [comment]
How can i have FirstFieldWithLeftImageAndBottomLayer textfield?

My concern is BOTTOM LAYER...

**Comment by Sahilberi** [comment]
Simply select the Bottom Color to your choice color in Attributes inspector.
