### ISSUE TITLE
get "Use of undeclared type 'ImageTextField' " error on view controller

### ISSUE THREAD

**Issue by MahdiFarzami** [Sahilberi/ImageTextField#3]
i get this error when i try to link imageTextField from designer to viewcontroller

**Comment by Sahilberi** [comment]
can you add screenshots where the error is occurring?

**Comment by MahdiFarzami** [comment]
![error](https://user-images.githubusercontent.com/3367690/28236594-97a2fb2a-693e-11e7-9adc-e88ca135319e.png)

@Sahilberi

**Comment by Sahilberi** [comment]
I think   ImageTextField is not successfully added through the pod.
try adding this line in pod file and run command pod update 
pod 'ImageTextField','~> 1.0.0'
also, you can add manually  ImageTextField.swift into your project.
