### ISSUE TITLE
Unable to find a specification for `ImageTextField (~> 1.0.0)`

### ISSUE THREAD

**Issue by tomaspolz** [Sahilberi/ImageTextField#4]
Hi, i am getting errorUnable to find a specification for `ImageTextField (~> 1.0.0)` while trying to install via coccoapod install option. Do you know where could by the problem ?

My Podfile looks like this:
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XYZ' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nebouram
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Alamofire', '~> 4.4'
  pod 'SwiftyJSON'
  pod 'SideMenu'
  pod 'DLRadioButton', '~> 1.4'
  pod 'ImageTextField','~> 1.0.0'
end

```

**Comment by HamentM** [comment]
Seems like, It did't have any problem. We have copied your podfile code to our pod file, Its run and integrated all libraries successfully.
Can u please describe bit more about your problem or Can u provide your pod file?
Or u may find solution of your problem from this link
[https://stackoverflow.com/questions/40102061/cocoapods-unable-to-find-a-specification-for-firebase-core](https://stackoverflow.com/questions/40102061/cocoapods-unable-to-find-a-specification-for-firebase-core)

Thanks.

**Comment by tomaspolz** [comment]
Yeah, i found answer in the given link. 
`pod repo update`
did the trick.

Thank you ;-)

**Comment by Sahilberi** [comment]
Thanks, @HamentM .
